name: madsnorgaard.net
type: php
docroot: ""
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.4"
use_dns_when_possible: true
composer_version: "2"
nodejs_version: "22"
web_environment:
    - DRUPAL_BASE_URL=https://drupal.madsnorgaard.net.ddev.site
    - PHOTO_SITE_URL=https://photo.madsnorgaard.net
